---
abstract: 'Simple Monitoring Tools'
author:
  - 'Lepenkov Sergey (Serz Minus) <minus@mail333.com>'
build_requires:
  ExtUtils::MakeMaker: 6.6
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.96, CPAN::Meta::Converter version 2.120921'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-MonM
no_index:
  directory:
    - t
    - inc
recommends:
  Data::Dumper: 0
requires:
  CTK: 1.16
  Class::C3::Adopt::NEXT: 0.13
  DBI: 1.6
  Data::Dumper: 0
  File::Copy: 2.18
  File::Find: 1.15
  File::Path: 2
  HTTP::Cookies: 6
  HTTP::Message: 6.02
  JSON: 2.53
  LWP: 5.8
  LWP::MediaTypes: 6
  LWP::UserAgent: 5.8
  Mail::POP3Client: 2.18
  Net::Ping: 2.36
  Net::SMTP: 2.31
  Net::Telnet: 3.03
  Text::SimpleTable: 2.03
  Text::Unidecode: 0.04
  Try::Tiny: 0.07
  URI: 1.5
  WWW::MLite: 1.05
  XML::Simple: 2.2
  YAML::Tiny: 1.5
  perl: 5.008001
resources:
  homepage: http://app-monm.sourceforge.net
  license: http://opensource.org/licenses/gpl-license.php
  repository: https://svn.code.sf.net/p/app-monm/code/trunk
version: 1.00
